# Generated by Django 4.1.7 on 2023-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes_title', models.CharField(max_length=500, verbose_name='Кодекс аты')),
                ('description', models.TextField(blank=True, verbose_name='Бап')),
                ('code_text', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Кодекс',
                'verbose_name_plural': 'Кодекстер',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laws_title', models.CharField(max_length=500, verbose_name='Зан аты')),
                ('description', models.TextField(blank=True, verbose_name='Бап')),
                ('laws_text', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Заң',
                'verbose_name_plural': 'Заңдар',
                'ordering': ['id'],
            },
        ),
    ]
