# Generated by Django 4.1.7 on 2023-04-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('number', models.CharField(max_length=100, verbose_name='Телефон номері')),
                ('title', models.CharField(max_length=100, verbose_name='Мәселе')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Өтінім',
                'verbose_name_plural': 'Байланыс өтінімдері',
                'ordering': ['id'],
            },
        ),
    ]
