# Generated by Django 4.2 on 2024-01-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0002_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Codes',
        ),
        migrations.DeleteModel(
            name='Laws',
        ),
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.RemoveField(
            model_name='request',
            name='number',
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
